/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Automation;

import static org.junit.Assert.assertTrue;

import org.junit.Test;

import automation.Library;

public class LibraryTest {
	@Test
	public void testSomeLibraryMethod() {
		Library classUnderTest = new Library();
		assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
	}
}
